### ISSUE TITLE
Help Required - Debug Perl under Apache

### ISSUE THREAD

**Issue by akjohnston** [Camelcade/Perl5-IDEA#1771]
Hi,
I am a newbie on Perl, but an experienced IntelliJ user for web development in other languages (Java, Python). I have been asked to maintain a web site which uses Perl under Apache for the backend, and I am hoping I can set up debugging the same way as for other languages. I have looked into the Wiki and it looks like this should be possible, but I can't get it to work and would appreciate some help.

Does anyone have a working example / instructions of how to set this up, and run it so that the web code runs freely but stops on any breakpoint in the Perl code?

Thanks
Andrew

Here are my environment details, but I'm not sure they will help:
- IntelliJ IDEA 2018.1.1 (Ultimate Edition) Build #IU-181.4445.78
- Linux 4.13.0-38-generic
- Perl plugin 2018.1.1
- Ubuntu 16 desktop (I can also run remote debugging from Windows 10, but it's probably sensible to focus on the Linux system first)

**Comment by hurricup** [comment]
Probably this may be helpful: https://github.com/Camelcade/Perl5-IDEA-Debugger/pull/26

**Comment by hurricup** [comment]
That pull request been done for that exact purpose if I remember right. To be able to debug web server. Seems there is no `how to` guide. 

As far as I remember you need to configure apache to use a single thread and configure `mod_perl` to run in debug mode.

**Comment by mbarbon** [comment]
I released https://metacpan.org/release/Apache2-Camelcadedb which should help with debugging under mod_perl. and https://metacpan.org/release/Plack-Middleware-Camelcadedb to help debugging under Plack.

Both are thin wrappers around Devel::Camelcadedb.

**Comment by hurricup** [comment]
Awesome! Docs for modules could be improved though. Also few lines on how to use it step by step would be really nice!

**Comment by lectobenzene** [comment]
@akjohnston Where you able to accomplish this? Were you able to attache the debugger to a running web server?

**Comment by akjohnston** [comment]
Partly. Unfortunately I can't confirm exactly as it's been a couple of months, I'm currently away from home and I'll have to check exactly where I got to when I'm back on my other PC next week. I'll update again then.

Working with @mbarbon I established that we need to “patch” ModPerl::RegistryCooker::convert_script_to_compiled_handler. In practice RegistryCooker is a single-file module, which can be readily sub-classed following the guidance in https://perl.apache.org/docs/2.0/api/ModPerl/RegistryCooker.html . Registry and RegistryBB are two such sub-classes. The code for each is downloadable (e.g. “source” link at the top of http://search.cpan.org/dist/mod_perl/docs/api/ModPerl/Registry.pod).

The solution is along the lines of:
1. Create a new subclass of RegistryCooker e.g. “RegistryDebug”, probably based on “Registry” as this explicitly manages which methods are subclassed and which go to the base
2. In this new module, create an override for convert_script_to_compiled_handler based on the RegistryCooker version but modified as per the guidance 
3. Build and install the RegistryDebug module 
4. Modify the application's vhost .conf file so that instead of using RegistryBB I use RegistryDebug

I will check next week and report on my progress, but it would be great if we could find a way to integrate the updated version of Registry() into the plugin.

**Comment by akjohnston** [comment]
Confirmed that this is still not working for me, despite upgrading to latest IntelliJ, perl and plugin.

**Comment by toolowner** [comment]
@akjohnston is there any good news?
